### ISSUE TITLE
react/cache v1.x compatibility

### ISSUE THREAD

**Issue by SQKo** [seregazhuk/php-react-cache-memcached#11]
Hello! Is there any plan to update this library to use [react/cache](https://github.com/reactphp/cache) ^1.0?

It seems not working right now since it does not implement the PSR-16 compatible methods;
```
PHP Fatal error:  Class seregazhuk\React\Cache\Memcached\Memcached contains 5 abstract methods and must therefore be declared abstract or implement the remaining methods (React\Cache\CacheInterface::getMultiple, React\Cache\CacheInterface::setMultiple, React\Cache\CacheInterface::deleteMultiple, ...) in /home/runner/work/DiscordPHP/DiscordPHP/vendor/seregazhuk/react-cache-memcached/src/Memcached.php on line 10
```

I'm currently working on PHP 7.4 - 8.1, planning to use it on a library that'd provides react/cache options either [redis](https://github.com/WyriHaximus/reactphp-cache-redis) or memcached (this)

Some other dependency requirements if possible:
```
Using version ^1.0 for seregazhuk/react-cache-memcached
./composer.json has been updated
Running composer update seregazhuk/react-cache-memcached
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - seregazhuk/react-cache-memcached 1.0.2 requires seregazhuk/react-memcached ^0.2 -> satisfiable by seregazhuk/react-memcached[v0.2.0, 0.2.1].
    - seregazhuk/react-cache-memcached[v1.0.0, ..., v1.0.1] require react/cache ^0.4.1 -> found react/cache[v0.4.1, v0.4.2] but it conflicts with your root composer.json require (^1.1).
    - seregazhuk/react-memcached v0.2.0 requires react/socket ^0.8 -> found react/socket[v0.8.0, ..., v0.8.12] but the package is fixed to v1.11.0 (lock file 
version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - seregazhuk/react-memcached 0.2.1 requires evenement/evenement 3 -> found evenement/evenement[3.0.0] but the package is fixed to v3.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires seregazhuk/react-cache-memcached ^1.0 -> satisfiable by seregazhuk/react-cache-memcached[v1.0.0, v1.0.1, 1.0.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require seregazhuk/react-cache-memcached:*" to figure out if 
any version is installable, or "composer require seregazhuk/react-cache-memcached:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by SQKo** [comment]
Another issue: Using `$cache->get()` will throw error when key does not exists (https://github.com/seregazhuk/php-react-memcached/issues/19). Without ability to catch the error nor even the rejection, this whole library is meaningless!
